apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  selector:
    matchLabels:
      io.kompose.service: consumer
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: consumer
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: d1zov/microservicesconsumer:latest
          name: consumer
          ports:
            - containerPort: 80
              hostPort: 4999
              protocol: TCP
      restartPolicy: Always
