apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  selector:
    matchLabels:
      io.kompose.service: proxy
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: proxy
    spec:
      containers:
        - image: nginx:latest
          name: lab-proxy
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: proxy-claim0
      restartPolicy: Always
      volumes:
        - name: proxy-claim0
          persistentVolumeClaim:
            claimName: proxy-claim0
