apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: usersservice
  name: usersservice
spec:
  ports:
    - name: "57860"
      port: 57860
      targetPort: 80
  selector:
    io.kompose.service: usersservice
