apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: usersservice
  name: usersservice
spec:
  selector:
    matchLabels:
      io.kompose.service: usersservice
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: usersservice
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: d1zov/microservicesusersservice:latest
          name: user-service
          ports:
            - containerPort: 80
              hostPort: 57860
              protocol: TCP
      restartPolicy: Always
