version: '3.4'

networks:
  labs:
    driver: bridge

services:
  usersservice:
    image: ${DOCKER_REGISTRY-}microservicesusersservice
    networks:
      - labs
    build:
      context: .
      dockerfile: Microservices.UsersService/Dockerfile

  labservice:
    image: ${DOCKER_REGISTRY-}microserviceslabservice
    networks:
      - labs
    build:
      context: .
      dockerfile: Microservices.LabService/Dockerfile
  
  proxy:
    image: nginx:latest
    networks:
      - labs
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
