version: '3.9'

networks:
  labs:
    driver: bridge

volumes:
  elasticsearch-data:
  pgdata:
    driver: local

services:
  usersservice:
    container_name: user_service
    image: ${DOCKER_REGISTRY-}microservicesusersservice
    networks:
      - labs
    build:
      context: .
      dockerfile: Microservices.UsersService/Dockerfile
    depends_on:
      - db
      - rabbit
    restart: always

  labservice:
    container_name: lab_service
    image: ${DOCKER_REGISTRY-}microserviceslabservice
    depends_on:
     - rabbit
    networks:
      - labs
    build:
      context: .
      dockerfile: Microservices.LabService/Dockerfile
    restart: always
  
  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: laba
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - labs
    restart: always
  
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    hostname: "messageBroker"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - labs
    restart: always
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq

  proxy:
    image: nginx:latest
    container_name: lab_proxy
    networks:
      - labs
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - labs

  kibana:
    container_name: kibana
    image: kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - labs

  consumer:
    container_name: consumer
    image: ${DOCKER_REGISTRY-}microservicesconsumer
    restart: always
    networks:
      - labs
    depends_on:
      - rabbit
    build:
      context: .
      dockerfile: Microservices.Consumer/Dockerfile

