apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 4;

    events { worker_connections 1024; }

    http {
        server {
            listen 80;

            location ~ ^/api/users {
                proxy_pass         http://usersservice:80;
            }

            location ~ ^/api/service {
                proxy_pass         http://labservice:80;
            }
        }
    }
